services:
  db:
    image: postgres:17.4-alpine3.21
    env_file:
      - ../.env
    ports:
      - 5432:5432
    volumes:
      - ./config:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
